import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Download, FileSpreadsheet, FileText, FileJson } from "lucide-react";
import { PageHead, Panel, Table, Pill } from "@/components/recruiter/reportsUi";

export const Route = createFileRoute("/recruiter/reports/exports")({
  head: () => ({ meta: [{ title: "Export History — Yuvro Recruiter" }, { name: "robots", content: "noindex" }] }),
  component: ExportHistory,
});

interface Exp { id: string; name: string; format: "CSV" | "PDF" | "JSON"; scope: string; size: string; by: string; when: string; status: "Ready" | "Processing" | "Expired" }

const SEED: Exp[] = [
  { id: "1", name: "Backend Java L2 — candidates", format: "CSV", scope: "1,000 rows", size: "412 KB", by: "You", when: "Today, 10:24", status: "Ready" },
  { id: "2", name: "Weekly hiring summary", format: "PDF", scope: "All evaluations", size: "1.2 MB", by: "You", when: "Yesterday, 18:02", status: "Ready" },
  { id: "3", name: "Shortlist export", format: "JSON", scope: "84 rows", size: "96 KB", by: "Talent Ops", when: "3d ago", status: "Expired" },
];

const icon = (f: Exp["format"]) => (f === "CSV" ? <FileSpreadsheet className="h-3.5 w-3.5" /> : f === "PDF" ? <FileText className="h-3.5 w-3.5" /> : <FileJson className="h-3.5 w-3.5" />);

function ExportHistory() {
  const [rows, setRows] = useState<Exp[]>(SEED);

  const newExport = (format: Exp["format"]) => {
    const id = String(Date.now());
    setRows(rs => [{ id, name: "Custom report export", format, scope: "All evaluations", size: "—", by: "You", when: "just now", status: "Processing" }, ...rs]);
    setTimeout(() => setRows(rs => rs.map(r => (r.id === id ? { ...r, status: "Ready", size: "318 KB" } : r))), 1400);
  };

  return (
    <div className="space-y-6">
      <PageHead
        title="Export History"
        desc="Every report export generated from this workspace."
        action={
          <div className="flex items-center gap-2">
            {(["CSV", "PDF", "JSON"] as const).map(f => (
              <button key={f} onClick={() => newExport(f)} className="inline-flex items-center gap-1.5 rounded-lg border border-black/10 px-3 py-2 text-[12px] text-neutral-700 hover:border-black/25 hover:text-neutral-900">
                <Download className="h-3.5 w-3.5" /> {f}
              </button>
            ))}
          </div>
        }
      />
      <Panel>
        <Table
          head={["Export", "Format", "Scope", "Size", "Generated by", "When", "Status"]}
          rows={rows.map(r => [
            <span className="font-medium">{r.name}</span>,
            <span className="inline-flex items-center gap-1.5">{icon(r.format)} {r.format}</span>,
            r.scope,
            r.size,
            r.by,
            r.when,
            <Pill tone={r.status === "Ready" ? "green" : r.status === "Processing" ? "amber" : "neutral"}>{r.status}</Pill>,
          ])}
        />
      </Panel>
    </div>
  );
}
