/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as CollaborationRouteImport } from './routes/collaboration'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollaborationIndexRouteImport } from './routes/collaboration.index'
import { Route as LabSlugRouteImport } from './routes/lab.$slug'
import { Route as CollaborationSquadsRouteImport } from './routes/collaboration.squads'
import { Route as CollaborationRequestsRouteImport } from './routes/collaboration.requests'
import { Route as CollaborationReputationRouteImport } from './routes/collaboration.reputation'
import { Route as CollaborationRankingsRouteImport } from './routes/collaboration.rankings'
import { Route as CollaborationPairRouteImport } from './routes/collaboration.pair'
import { Route as CollaborationMarketplaceRouteImport } from './routes/collaboration.marketplace'
import { Route as CollaborationLiveRouteImport } from './routes/collaboration.live'
import { Route as CollaborationInvitationsRouteImport } from './routes/collaboration.invitations'
import { Route as CollaborationIncidentsRouteImport } from './routes/collaboration.incidents'
import { Route as CollaborationDiscoverRouteImport } from './routes/collaboration.discover'
import { Route as CollaborationCreateRouteImport } from './routes/collaboration.create'
import { Route as CollaborationWorkspaceIdRouteImport } from './routes/collaboration.workspace.$id'
import { Route as CollaborationSquadIdRouteImport } from './routes/collaboration.squad.$id'
import { Route as CollaborationEngineerIdRouteImport } from './routes/collaboration.engineer.$id'
import { Route as LabSlugTicketTicketIdRouteImport } from './routes/lab.$slug.ticket.$ticketId'
import { Route as LabSlugTicketTicketIdReviewRouteImport } from './routes/lab.$slug.ticket.$ticketId.review'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationRoute = CollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationIndexRoute = CollaborationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollaborationRoute,
} as any)
const LabSlugRoute = LabSlugRouteImport.update({
  id: '/lab/$slug',
  path: '/lab/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationSquadsRoute = CollaborationSquadsRouteImport.update({
  id: '/squads',
  path: '/squads',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationRequestsRoute = CollaborationRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationReputationRoute = CollaborationReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationRankingsRoute = CollaborationRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationPairRoute = CollaborationPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationMarketplaceRoute =
  CollaborationMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => CollaborationRoute,
  } as any)
const CollaborationLiveRoute = CollaborationLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationInvitationsRoute =
  CollaborationInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => CollaborationRoute,
  } as any)
const CollaborationIncidentsRoute = CollaborationIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationDiscoverRoute = CollaborationDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationCreateRoute = CollaborationCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationWorkspaceIdRoute =
  CollaborationWorkspaceIdRouteImport.update({
    id: '/workspace/$id',
    path: '/workspace/$id',
    getParentRoute: () => CollaborationRoute,
  } as any)
const CollaborationSquadIdRoute = CollaborationSquadIdRouteImport.update({
  id: '/squad/$id',
  path: '/squad/$id',
  getParentRoute: () => CollaborationRoute,
} as any)
const CollaborationEngineerIdRoute = CollaborationEngineerIdRouteImport.update({
  id: '/engineer/$id',
  path: '/engineer/$id',
  getParentRoute: () => CollaborationRoute,
} as any)
const LabSlugTicketTicketIdRoute = LabSlugTicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => LabSlugRoute,
} as any)
const LabSlugTicketTicketIdReviewRoute =
  LabSlugTicketTicketIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => LabSlugTicketTicketIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/collaboration': typeof CollaborationRouteWithChildren
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/collaboration/create': typeof CollaborationCreateRoute
  '/collaboration/discover': typeof CollaborationDiscoverRoute
  '/collaboration/incidents': typeof CollaborationIncidentsRoute
  '/collaboration/invitations': typeof CollaborationInvitationsRoute
  '/collaboration/live': typeof CollaborationLiveRoute
  '/collaboration/marketplace': typeof CollaborationMarketplaceRoute
  '/collaboration/pair': typeof CollaborationPairRoute
  '/collaboration/rankings': typeof CollaborationRankingsRoute
  '/collaboration/reputation': typeof CollaborationReputationRoute
  '/collaboration/requests': typeof CollaborationRequestsRoute
  '/collaboration/squads': typeof CollaborationSquadsRoute
  '/lab/$slug': typeof LabSlugRouteWithChildren
  '/collaboration/': typeof CollaborationIndexRoute
  '/collaboration/engineer/$id': typeof CollaborationEngineerIdRoute
  '/collaboration/squad/$id': typeof CollaborationSquadIdRoute
  '/collaboration/workspace/$id': typeof CollaborationWorkspaceIdRoute
  '/lab/$slug/ticket/$ticketId': typeof LabSlugTicketTicketIdRouteWithChildren
  '/lab/$slug/ticket/$ticketId/review': typeof LabSlugTicketTicketIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/collaboration/create': typeof CollaborationCreateRoute
  '/collaboration/discover': typeof CollaborationDiscoverRoute
  '/collaboration/incidents': typeof CollaborationIncidentsRoute
  '/collaboration/invitations': typeof CollaborationInvitationsRoute
  '/collaboration/live': typeof CollaborationLiveRoute
  '/collaboration/marketplace': typeof CollaborationMarketplaceRoute
  '/collaboration/pair': typeof CollaborationPairRoute
  '/collaboration/rankings': typeof CollaborationRankingsRoute
  '/collaboration/reputation': typeof CollaborationReputationRoute
  '/collaboration/requests': typeof CollaborationRequestsRoute
  '/collaboration/squads': typeof CollaborationSquadsRoute
  '/lab/$slug': typeof LabSlugRouteWithChildren
  '/collaboration': typeof CollaborationIndexRoute
  '/collaboration/engineer/$id': typeof CollaborationEngineerIdRoute
  '/collaboration/squad/$id': typeof CollaborationSquadIdRoute
  '/collaboration/workspace/$id': typeof CollaborationWorkspaceIdRoute
  '/lab/$slug/ticket/$ticketId': typeof LabSlugTicketTicketIdRouteWithChildren
  '/lab/$slug/ticket/$ticketId/review': typeof LabSlugTicketTicketIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/certificates': typeof CertificatesRoute
  '/collaboration': typeof CollaborationRouteWithChildren
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/collaboration/create': typeof CollaborationCreateRoute
  '/collaboration/discover': typeof CollaborationDiscoverRoute
  '/collaboration/incidents': typeof CollaborationIncidentsRoute
  '/collaboration/invitations': typeof CollaborationInvitationsRoute
  '/collaboration/live': typeof CollaborationLiveRoute
  '/collaboration/marketplace': typeof CollaborationMarketplaceRoute
  '/collaboration/pair': typeof CollaborationPairRoute
  '/collaboration/rankings': typeof CollaborationRankingsRoute
  '/collaboration/reputation': typeof CollaborationReputationRoute
  '/collaboration/requests': typeof CollaborationRequestsRoute
  '/collaboration/squads': typeof CollaborationSquadsRoute
  '/lab/$slug': typeof LabSlugRouteWithChildren
  '/collaboration/': typeof CollaborationIndexRoute
  '/collaboration/engineer/$id': typeof CollaborationEngineerIdRoute
  '/collaboration/squad/$id': typeof CollaborationSquadIdRoute
  '/collaboration/workspace/$id': typeof CollaborationWorkspaceIdRoute
  '/lab/$slug/ticket/$ticketId': typeof LabSlugTicketTicketIdRouteWithChildren
  '/lab/$slug/ticket/$ticketId/review': typeof LabSlugTicketTicketIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/certificates'
    | '/collaboration'
    | '/forum'
    | '/leaderboard'
    | '/profile'
    | '/collaboration/create'
    | '/collaboration/discover'
    | '/collaboration/incidents'
    | '/collaboration/invitations'
    | '/collaboration/live'
    | '/collaboration/marketplace'
    | '/collaboration/pair'
    | '/collaboration/rankings'
    | '/collaboration/reputation'
    | '/collaboration/requests'
    | '/collaboration/squads'
    | '/lab/$slug'
    | '/collaboration/'
    | '/collaboration/engineer/$id'
    | '/collaboration/squad/$id'
    | '/collaboration/workspace/$id'
    | '/lab/$slug/ticket/$ticketId'
    | '/lab/$slug/ticket/$ticketId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/certificates'
    | '/forum'
    | '/leaderboard'
    | '/profile'
    | '/collaboration/create'
    | '/collaboration/discover'
    | '/collaboration/incidents'
    | '/collaboration/invitations'
    | '/collaboration/live'
    | '/collaboration/marketplace'
    | '/collaboration/pair'
    | '/collaboration/rankings'
    | '/collaboration/reputation'
    | '/collaboration/requests'
    | '/collaboration/squads'
    | '/lab/$slug'
    | '/collaboration'
    | '/collaboration/engineer/$id'
    | '/collaboration/squad/$id'
    | '/collaboration/workspace/$id'
    | '/lab/$slug/ticket/$ticketId'
    | '/lab/$slug/ticket/$ticketId/review'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/certificates'
    | '/collaboration'
    | '/forum'
    | '/leaderboard'
    | '/profile'
    | '/collaboration/create'
    | '/collaboration/discover'
    | '/collaboration/incidents'
    | '/collaboration/invitations'
    | '/collaboration/live'
    | '/collaboration/marketplace'
    | '/collaboration/pair'
    | '/collaboration/rankings'
    | '/collaboration/reputation'
    | '/collaboration/requests'
    | '/collaboration/squads'
    | '/lab/$slug'
    | '/collaboration/'
    | '/collaboration/engineer/$id'
    | '/collaboration/squad/$id'
    | '/collaboration/workspace/$id'
    | '/lab/$slug/ticket/$ticketId'
    | '/lab/$slug/ticket/$ticketId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CertificatesRoute: typeof CertificatesRoute
  CollaborationRoute: typeof CollaborationRouteWithChildren
  ForumRoute: typeof ForumRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  LabSlugRoute: typeof LabSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration': {
      id: '/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof CollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration/': {
      id: '/collaboration/'
      path: '/'
      fullPath: '/collaboration/'
      preLoaderRoute: typeof CollaborationIndexRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/lab/$slug': {
      id: '/lab/$slug'
      path: '/lab/$slug'
      fullPath: '/lab/$slug'
      preLoaderRoute: typeof LabSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration/squads': {
      id: '/collaboration/squads'
      path: '/squads'
      fullPath: '/collaboration/squads'
      preLoaderRoute: typeof CollaborationSquadsRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/requests': {
      id: '/collaboration/requests'
      path: '/requests'
      fullPath: '/collaboration/requests'
      preLoaderRoute: typeof CollaborationRequestsRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/reputation': {
      id: '/collaboration/reputation'
      path: '/reputation'
      fullPath: '/collaboration/reputation'
      preLoaderRoute: typeof CollaborationReputationRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/rankings': {
      id: '/collaboration/rankings'
      path: '/rankings'
      fullPath: '/collaboration/rankings'
      preLoaderRoute: typeof CollaborationRankingsRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/pair': {
      id: '/collaboration/pair'
      path: '/pair'
      fullPath: '/collaboration/pair'
      preLoaderRoute: typeof CollaborationPairRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/marketplace': {
      id: '/collaboration/marketplace'
      path: '/marketplace'
      fullPath: '/collaboration/marketplace'
      preLoaderRoute: typeof CollaborationMarketplaceRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/live': {
      id: '/collaboration/live'
      path: '/live'
      fullPath: '/collaboration/live'
      preLoaderRoute: typeof CollaborationLiveRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/invitations': {
      id: '/collaboration/invitations'
      path: '/invitations'
      fullPath: '/collaboration/invitations'
      preLoaderRoute: typeof CollaborationInvitationsRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/incidents': {
      id: '/collaboration/incidents'
      path: '/incidents'
      fullPath: '/collaboration/incidents'
      preLoaderRoute: typeof CollaborationIncidentsRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/discover': {
      id: '/collaboration/discover'
      path: '/discover'
      fullPath: '/collaboration/discover'
      preLoaderRoute: typeof CollaborationDiscoverRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/create': {
      id: '/collaboration/create'
      path: '/create'
      fullPath: '/collaboration/create'
      preLoaderRoute: typeof CollaborationCreateRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/workspace/$id': {
      id: '/collaboration/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/collaboration/workspace/$id'
      preLoaderRoute: typeof CollaborationWorkspaceIdRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/squad/$id': {
      id: '/collaboration/squad/$id'
      path: '/squad/$id'
      fullPath: '/collaboration/squad/$id'
      preLoaderRoute: typeof CollaborationSquadIdRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/collaboration/engineer/$id': {
      id: '/collaboration/engineer/$id'
      path: '/engineer/$id'
      fullPath: '/collaboration/engineer/$id'
      preLoaderRoute: typeof CollaborationEngineerIdRouteImport
      parentRoute: typeof CollaborationRoute
    }
    '/lab/$slug/ticket/$ticketId': {
      id: '/lab/$slug/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/lab/$slug/ticket/$ticketId'
      preLoaderRoute: typeof LabSlugTicketTicketIdRouteImport
      parentRoute: typeof LabSlugRoute
    }
    '/lab/$slug/ticket/$ticketId/review': {
      id: '/lab/$slug/ticket/$ticketId/review'
      path: '/review'
      fullPath: '/lab/$slug/ticket/$ticketId/review'
      preLoaderRoute: typeof LabSlugTicketTicketIdReviewRouteImport
      parentRoute: typeof LabSlugTicketTicketIdRoute
    }
  }
}

interface CollaborationRouteChildren {
  CollaborationCreateRoute: typeof CollaborationCreateRoute
  CollaborationDiscoverRoute: typeof CollaborationDiscoverRoute
  CollaborationIncidentsRoute: typeof CollaborationIncidentsRoute
  CollaborationInvitationsRoute: typeof CollaborationInvitationsRoute
  CollaborationLiveRoute: typeof CollaborationLiveRoute
  CollaborationMarketplaceRoute: typeof CollaborationMarketplaceRoute
  CollaborationPairRoute: typeof CollaborationPairRoute
  CollaborationRankingsRoute: typeof CollaborationRankingsRoute
  CollaborationReputationRoute: typeof CollaborationReputationRoute
  CollaborationRequestsRoute: typeof CollaborationRequestsRoute
  CollaborationSquadsRoute: typeof CollaborationSquadsRoute
  CollaborationIndexRoute: typeof CollaborationIndexRoute
  CollaborationEngineerIdRoute: typeof CollaborationEngineerIdRoute
  CollaborationSquadIdRoute: typeof CollaborationSquadIdRoute
  CollaborationWorkspaceIdRoute: typeof CollaborationWorkspaceIdRoute
}

const CollaborationRouteChildren: CollaborationRouteChildren = {
  CollaborationCreateRoute: CollaborationCreateRoute,
  CollaborationDiscoverRoute: CollaborationDiscoverRoute,
  CollaborationIncidentsRoute: CollaborationIncidentsRoute,
  CollaborationInvitationsRoute: CollaborationInvitationsRoute,
  CollaborationLiveRoute: CollaborationLiveRoute,
  CollaborationMarketplaceRoute: CollaborationMarketplaceRoute,
  CollaborationPairRoute: CollaborationPairRoute,
  CollaborationRankingsRoute: CollaborationRankingsRoute,
  CollaborationReputationRoute: CollaborationReputationRoute,
  CollaborationRequestsRoute: CollaborationRequestsRoute,
  CollaborationSquadsRoute: CollaborationSquadsRoute,
  CollaborationIndexRoute: CollaborationIndexRoute,
  CollaborationEngineerIdRoute: CollaborationEngineerIdRoute,
  CollaborationSquadIdRoute: CollaborationSquadIdRoute,
  CollaborationWorkspaceIdRoute: CollaborationWorkspaceIdRoute,
}

const CollaborationRouteWithChildren = CollaborationRoute._addFileChildren(
  CollaborationRouteChildren,
)

interface LabSlugTicketTicketIdRouteChildren {
  LabSlugTicketTicketIdReviewRoute: typeof LabSlugTicketTicketIdReviewRoute
}

const LabSlugTicketTicketIdRouteChildren: LabSlugTicketTicketIdRouteChildren = {
  LabSlugTicketTicketIdReviewRoute: LabSlugTicketTicketIdReviewRoute,
}

const LabSlugTicketTicketIdRouteWithChildren =
  LabSlugTicketTicketIdRoute._addFileChildren(
    LabSlugTicketTicketIdRouteChildren,
  )

interface LabSlugRouteChildren {
  LabSlugTicketTicketIdRoute: typeof LabSlugTicketTicketIdRouteWithChildren
}

const LabSlugRouteChildren: LabSlugRouteChildren = {
  LabSlugTicketTicketIdRoute: LabSlugTicketTicketIdRouteWithChildren,
}

const LabSlugRouteWithChildren =
  LabSlugRoute._addFileChildren(LabSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CertificatesRoute: CertificatesRoute,
  CollaborationRoute: CollaborationRouteWithChildren,
  ForumRoute: ForumRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  LabSlugRoute: LabSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
